apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-alpha
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2 # Two replicas for development
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: franklynux/daychecker:v1.0.0-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3002 # Default nodejs port for development
          env:  
            - name: ENVIRONMENT
              value: "development"
            - name: PORT
              value: "3002"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
