apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# This is the staging overlay for the web application.

resources:
  - ../../base

nameSuffix: -staging

patches:
  - path: patch.yaml
  - path: service.yaml

configMapGenerator:
  - name: webapp-config
    behavior: merge
    literals:
      - APP_MODE=staging
      - APP_VERSION=1.0.0
      - LOG_LEVEL=debug
      - FEATURE_FLAG=false
secretGenerator:
  - name: webapp-secret
    behavior: merge
    literals:
      - DB_PASSWORD=stagingchangeme
      - API_KEY=stagingchangeme
    type: Opaque

transformers:
  - labels-transformer.yaml