apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - name: staging-port
      protocol: TCP
      port: 3003
      targetPort: 3003
  type: LoadBalancer