apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
# This is the production overlay for the web application.

resources:
  - ../../base # Base resources to inherit from

nameSuffix: -prod # Suffix to differentiate production resources

patches: 
  # Patches to modify existing resources in production
  - path: patch.yaml # Patch to modify deployment 
  - path: service.yaml # Patch to modify service 

configMapGenerator:
  - name: webapp-config
    behavior: merge # Merge behavior to combine with base config
    literals:
      - APP_MODE=production # Application mode for production
      - APP_VERSION=1.0.0 # Version for production
      - LOG_LEVEL=info # Log level for production
      - FEATURE_FLAG=false # Feature flag for production
secretGenerator:
  - name: webapp-secret
    behavior: merge
    literals:
      - DB_PASSWORD=prod_changeme # Database password for production
      - API_KEY=prod_changeme # API key for production
    # Type of secret, Opaque is the default type for generic secrets
    type: Opaque
    
transformers:
  - labels-transformer.yaml # Transformer to add common labels to all resources