apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: franklynux/daychecker:v1.0.0-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 3001 # Prod nodejs port
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: PORT
              value: "3001"
