apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-alpha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp-service-account
      containers:
        - name: webapp-container
          image: franklynux/daychecker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Default nodejs port
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: webapp-config
            - secretRef:
                name: webapp-secret
            
            
