apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - webapp-token-secret.yaml
# This is the base kustomization file for the web application.

configMapGenerator:
  - name: webapp-config
    literals:
      - APP_MODE=base
      - LOG_LEVEL=info
      - FEATURE_FLAG=false
secretGenerator:
  - name: webapp-secret
    literals:
      - DB_PASSWORD=changeme
      - API_KEY=changeme
    type: Opaque
  
transformers:
  - labels-transformer.yaml

