apiVersion: builtin
kind: LabelTransformer
metadata:
  name: add-common-labels
labels:
  app.kubernetes.io/managed-by: kustomize
  project: kustomize-project
  environment: base
fieldSpecs:
  - path: metadata/labels
    create: true
