apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - name: base-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer