name: Deploy to Kubernetes with Kustomize
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
        
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl cluster-info  # Verify connection
          
      - name: Deploy to environment
        run: |
          kustomize build overlays/dev | kubectl apply -f -