name: Deploy to Kubernetes with Kustomize
# This GitHub Actions workflow deploys a Kubernetes application using Kustomize.

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
        
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig
          
      - name: Deploy to environment
        run: |
          kubectl apply -k overlays/dev
